# lnx-debian-gnome-dr default configuration

BACKUP_ROOT="/media/thedataprofessor/4A21-0000/disaster-recovery"
RETENTION_COUNT="12"
COMPRESSION="zstd"

BACKUP_PERSONAL_FILES="false"
BACKUP_SSH_KEYS="true"
BACKUP_NETWORK_CONNECTIONS="true"
BACKUP_DOCKER_DATA="false"
