#!/usr/bin/env bash
set -Eeuo pipefail

umask 077

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION_FILE="${PROJECT_ROOT}/VERSION"

OUTPUT="-"
DRY_RUN=false

usage() {
    printf '%s\n' \
        "Usage:" \
        "  inventory.sh [--output FILE]" \
        "  inventory.sh --dry-run" \
        "  inventory.sh --help" \
        "" \
        "Options:" \
        "  --output FILE  Write the inventory to FILE." \
        "  --dry-run      Show the planned collection without executing it." \
        "  --help         Show this help."
}

while (($# > 0)); do
    case "$1" in
        --output)
            [[ $# -ge 2 ]] || {
                echo "ERROR: --output requires a file path." >&2
                exit 2
            }
            OUTPUT="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "ERROR: unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

PLAN=(
    "Machine and operating-system identity"
    "Desktop and session information"
    "CPU and memory"
    "Firmware and hardware model"
    "PCI and USB devices"
    "Storage devices, filesystems and mounts"
    "Network interfaces, routes and connection metadata"
    "Debian, Flatpak and Snap package inventories"
    "Enabled and failed systemd units"
    "Scheduled systemd timers"
    "Docker and Podman inventories"
    "NVIDIA, DRM KMS and Secure Boot state"
    "Kernel command line and boot configuration"
    "GNOME extensions"
    "Local users and groups"
)

if [[ "$DRY_RUN" == true ]]; then
    echo "DRY RUN — no commands will be executed."
    echo
    for item in "${PLAN[@]}"; do
        printf '  - %s\n' "$item"
    done
    exit 0
fi

section() {
    printf '\n\n## %s\n\n' "$1"
}

run_command() {
    local title="$1"
    shift

    section "$title"

    if ! command -v "$1" >/dev/null 2>&1; then
        printf '[SKIPPED] Command not installed: %s\n' "$1"
        return 0
    fi

    printf '$'
    printf ' %q' "$@"
    printf '\n\n'

    local status=0
    "$@" 2>&1 || status=$?

    if ((status != 0)); then
        printf '\n[UNAVAILABLE] Command exited with status %s.\n' "$status"
    fi

    return 0
}

run_shell() {
    local title="$1"
    local command_text="$2"

    section "$title"
    printf '$ %s\n\n' "$command_text"

    local status=0
    bash -o pipefail -lc "$command_text" 2>&1 || status=$?

    if ((status != 0)); then
        printf '\n[UNAVAILABLE] Collection exited with status %s.\n' "$status"
    fi

    return 0
}

TOOLKIT_VERSION="unknown"
if [[ -r "$VERSION_FILE" ]]; then
    TOOLKIT_VERSION="$(<"$VERSION_FILE")"
fi

TEMP_FILE="$(mktemp)"
trap 'rm -f "$TEMP_FILE"' EXIT

{
    printf '# Debian GNOME Workstation Inventory\n\n'
    printf 'Generated by: lnx-debian-gnome-dr\n\n'
    printf -- '- Toolkit version: %s\n' "$TOOLKIT_VERSION"
    printf -- '- Generated at: %s\n' "$(date --iso-8601=seconds)"
    printf -- '- Inventory user: %s\n' "$(id -un)"
    printf -- '- Effective user ID: %s\n' "$(id -u)"
    printf -- '- Hostname: %s\n' "$(hostname)"
    printf -- '- Read-only collection: yes\n'
    printf -- '- Credentials and private keys requested: no\n'
    printf -- '- Contains recovery-sensitive metadata: yes\n'

    run_command "Hostname and machine identity" hostnamectl
    run_command "Operating system release" cat /etc/os-release
    run_command "Kernel" uname -a
    run_command "Current user identity" id

    section "Desktop session"
    printf 'XDG_CURRENT_DESKTOP=%s\n' "${XDG_CURRENT_DESKTOP:-unknown}"
    printf 'XDG_SESSION_DESKTOP=%s\n' "${XDG_SESSION_DESKTOP:-unknown}"
    printf 'XDG_SESSION_TYPE=%s\n' "${XDG_SESSION_TYPE:-unknown}"
    printf 'WAYLAND_DISPLAY=%s\n' "${WAYLAND_DISPLAY:-not-set}"
    printf 'DISPLAY=%s\n' "${DISPLAY:-not-set}"

    run_command "GNOME version" gnome-shell --version
    run_command "CPU" lscpu
    run_command "Memory" free -h

    run_shell \
        "Firmware and hardware model" \
        'for file in sys_vendor product_name product_version product_serial bios_vendor bios_version bios_date; do
            path="/sys/class/dmi/id/${file}"
            if [[ -r "$path" ]]; then
                printf "%-18s %s\n" "${file}:" "$(cat "$path")"
            fi
        done'

    run_command "PCI devices and drivers" lspci -nnk
    run_command "USB devices" lsusb

    run_command \
        "Block devices and filesystems" \
        lsblk -e 7 -o NAME,PATH,TYPE,SIZE,FSTYPE,FSVER,LABEL,UUID,PARTUUID,MOUNTPOINTS,MODEL

    run_command "Linux software RAID status" cat /proc/mdstat

    section "Linux software RAID arrays"

    if ! command -v mdadm >/dev/null 2>&1; then
        echo "[SKIPPED] Command not installed: mdadm"
    elif ((EUID != 0)); then
        echo "[REQUIRES ROOT] Run the inventory as root to execute: mdadm --detail --scan"
    else
        printf '$ mdadm --detail --scan\n\n'

        mdadm_status=0
        mdadm --detail --scan 2>&1 || mdadm_status=$?

        if ((mdadm_status != 0)); then
            printf '\n[UNAVAILABLE] Command exited with status %s.\n' "$mdadm_status"
        fi
    fi

    run_command \
        "Mounted filesystems" \
        findmnt --real -o TARGET,SOURCE,FSTYPE,OPTIONS

    run_command "Filesystem capacity" df -hT
    run_command "Static filesystem configuration" cat /etc/fstab

    if command -v efibootmgr >/dev/null 2>&1; then
        run_command "UEFI boot entries" efibootmgr -v
    else
        section "UEFI boot entries"
        echo "[SKIPPED] Command not installed: efibootmgr"
    fi

    run_shell \
        "Mounted EFI system partition contents" \
        'if ! mountpoint -q /boot/efi; then
            echo "[UNAVAILABLE] /boot/efi is not mounted."
        elif [[ ! -r /boot/efi || ! -x /boot/efi ]]; then
            echo "[REQUIRES ROOT] /boot/efi is mounted but is not readable by the current user."
        elif [[ -d /boot/efi/EFI ]]; then
            find /boot/efi/EFI \
                -maxdepth 4 \
                -type f \
                -printf "%P\n" \
                | sort
        else
            echo "[UNAVAILABLE] /boot/efi is mounted, but the EFI directory does not exist."
        fi'

    run_command "Network interfaces" ip -brief address
    run_command "Network routes" ip route

    if command -v nmcli >/dev/null 2>&1; then
        run_command \
            "NetworkManager connection metadata without secrets" \
            nmcli --terse --fields NAME,UUID,TYPE,DEVICE connection show
    else
        section "NetworkManager connection metadata without secrets"
        echo "[SKIPPED] Command not installed: nmcli"
    fi

    run_shell \
        "Debian package inventory" \
        'dpkg-query -W -f="\${binary:Package}\t\${Version}\t\${db:Status-Abbrev}\n" | sort'

    run_shell \
        "Manually installed Debian packages" \
        'apt-mark showmanual | sort'

    if command -v flatpak >/dev/null 2>&1; then
        run_command \
            "Flatpak applications" \
            flatpak list --app --columns=application,branch,origin,installation
    else
        section "Flatpak applications"
        echo "[SKIPPED] Command not installed: flatpak"
    fi

    if command -v snap >/dev/null 2>&1; then
        run_command "Snap packages" snap list
    else
        section "Snap packages"
        echo "[SKIPPED] Command not installed: snap"
    fi

    run_command \
        "Enabled systemd units" \
        systemctl list-unit-files --state=enabled --no-pager

    run_command \
        "Failed systemd units" \
        systemctl --failed --no-pager

    run_command \
        "Systemd timers" \
        systemctl list-timers --all --no-pager

    if command -v docker >/dev/null 2>&1; then
        run_command "Docker version" docker version
        run_command "Docker containers" docker ps --all
        run_command "Docker images" docker image ls
        run_command "Docker volumes" docker volume ls
        run_command "Docker networks" docker network ls
    else
        section "Docker"
        echo "[SKIPPED] Command not installed: docker"
    fi

    if command -v podman >/dev/null 2>&1; then
        run_command "Podman version" podman version
        run_command "Podman containers" podman ps --all
        run_command "Podman images" podman image ls
    else
        section "Podman"
        echo "[SKIPPED] Command not installed: podman"
    fi

    if command -v nvidia-smi >/dev/null 2>&1; then
        run_command "NVIDIA status" nvidia-smi
    else
        section "NVIDIA status"
        echo "[SKIPPED] Command not installed: nvidia-smi"
    fi

    run_shell \
        "NVIDIA kernel driver" \
        'if [[ -r /proc/driver/nvidia/version ]]; then
            cat /proc/driver/nvidia/version
        else
            echo "[UNAVAILABLE] NVIDIA kernel driver information not found."
        fi'

    run_shell \
        "NVIDIA DRM modeset" \
        'parameter="/sys/module/nvidia_drm/parameters/modeset"

        if [[ -e "$parameter" ]]; then
            if cat "$parameter"; then
                :
            else
                echo "[UNAVAILABLE] Parameter exists but could not be read."
                ls -l "$parameter" 2>/dev/null || true
            fi
        elif grep -q "^nvidia_drm " /proc/modules 2>/dev/null; then
            echo "[UNAVAILABLE] nvidia_drm is loaded but does not expose the parameter."
        else
            echo "[UNAVAILABLE] nvidia_drm module is not loaded."
        fi

        printf "Kernel command line: "
        cat /proc/cmdline'

    if command -v mokutil >/dev/null 2>&1; then
        run_command "Secure Boot state" mokutil --sb-state
    else
        section "Secure Boot state"
        echo "[SKIPPED] Command not installed: mokutil"
    fi

    run_command "Kernel command line" cat /proc/cmdline
    run_command "GRUB defaults" cat /etc/default/grub

    if command -v gnome-extensions >/dev/null 2>&1; then
        run_command "Enabled GNOME extensions" gnome-extensions list --enabled
        run_command "All GNOME extensions" gnome-extensions list
    else
        section "GNOME extensions"
        echo "[SKIPPED] Command not installed: gnome-extensions"
    fi

    run_command "Local users" getent passwd
    run_command "Local groups" getent group

} >"$TEMP_FILE"

if [[ "$OUTPUT" == "-" ]]; then
    cat "$TEMP_FILE"
else
    mkdir -p "$(dirname "$OUTPUT")"
    install -m 600 "$TEMP_FILE" "$OUTPUT"
    printf 'Inventory written to: %s\n' "$OUTPUT"
fi
